### ISSUE TITLE
Accounting - Configuration - Exception If Input Is Incomplete

### ISSUE THREAD

**Issue by sam-adam** [sam-adam/Macsauto_w_Finance#14]
- ~~Define Account Type~~
  -  ![image](https://cloud.githubusercontent.com/assets/2836541/5793452/81092e50-9f76-11e4-8bbe-2df11231a82a.png)
  - Exception mesage: 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MacsautoIndonesia._001_13_Define_Account_Type.saveact() in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-13-Define_Account_Type.vb:line 25
   at MacsautoIndonesia._001_13_Define_Account_Type.BtnSave_Click(Object sender, EventArgs e) in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-13-Define_Account_Type.vb:line 15
```
- ~~Define Accounting Document~~
  - ![image](https://cloud.githubusercontent.com/assets/2836541/5793460/c0529f9c-9f76-11e4-9f2e-46b6d1ada91a.png)
  - Exception message:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MacsautoIndonesia._001_14_Acct_Doc_Type.saveact() in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-14-Acct_Doc_Type.vb:line 18
   at MacsautoIndonesia._001_14_Acct_Doc_Type.BtnSave_Click(Object sender, EventArgs e) in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-14-Acct_Doc_Type.vb:line 24
```
- Petty Cash Account
  - ![image](https://cloud.githubusercontent.com/assets/2836541/5793470/fd3ea4c8-9f76-11e4-9dda-1588f7e281dd.png)
  - Exception message: 

```
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at MacsautoIndonesia.Module1.ExecQueryNonReader(Object query) in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\999-Others\Module1.vb:line 36
   at MacsautoIndonesia._001_15_Petty_Cash_Config.saveSource1() in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-15-Petty_Cash_Config.vb:line 17
   at MacsautoIndonesia._001_15_Petty_Cash_Config.sourceBtn_Click(Object sender, EventArgs e) in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-15-Petty_Cash_Config.vb:line 81
```
- ![image](https://cloud.githubusercontent.com/assets/2836541/5793476/309de6b2-9f77-11e4-91d8-ea44663815bb.png)
- Exception message:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MacsautoIndonesia._001_15_Petty_Cash_Config.saveUsage() in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-15-Petty_Cash_Config.vb:line 48
   at MacsautoIndonesia._001_15_Petty_Cash_Config.BtnSave_Click(Object sender, EventArgs e) in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-15-Petty_Cash_Config.vb:line 89
```
- ~~Set accounting period~~
  - ![image](https://cloud.githubusercontent.com/assets/2836541/5793478/5704000c-9f77-11e4-8ce9-39fa8df7f911.png)
  - Exception message:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MacsautoIndonesia._001_17_Define_Accounting_Period.Button2_Click(Object sender, EventArgs e) in C:\Users\Sam\Documents\Visual Studio 2012\Projects\Macsauto_w_Finance\MacsautoIndonesia\001-Configuration\001-17-Define_Accounting_Period.vb:line 72
```

**Comment by sam-adam** [comment]
@surwijaya12 Ini gw assign ke u, tapi kita kerjain bareng aja. Dibikin sebisa mungkin rapih dan paksa user input dengan benar aja gan

**Comment by sam-adam** [comment]
@surwijaya12 Tolong updating yang pettycash config ya

**Comment by surwijaya12** [comment]
Updated, pettycash & accounting document type & accountType

**Comment by sam-adam** [comment]
@surwijaya12 Masih agak rentan gan sepertinya
1. Kalau Tab SourceAccount field PettyCashAccount dikosongin masih belum ada validasi, jadi exception
2. Table Usage kolom GLAccount masih editable jadi accountnya bisa diedit2 dan jadi gak valid
